### PR TITLE
Fix error caused by double-locking repo

### LINKED ISSUE #115: Lockfile detection failure on Debian
Using the last snapshot of source code, I compiled the tool on Debian Buster x86. But it is now impossible to migrate the repository because the locking engine reports the lockfile size is not zero. This issue happens also with the LevelDB datastore selected for the repository. So the only working one is BadgerDS but I am not able to use it on such an old machine. Do you know the possible workaround?

### PR DESCRIPTION
**Pull request by gammazero**
This fixes #115.

The repo was being double-locked, once by the migration and once by opening the repo.  However, on some platforms this double locking was not detected due to the combination of different locking implementations, and the defect was not detected by tests.

### CODE REVIEW

**Review by aschmahmann — APPROVED** [review]
LGTM. Although it might be a good idea to pull `fsrepo.Open` out of the `revertPins`/`transferPins` functions and pass in the repo so that it's obvious we have the repo lock when we do `mfsr.RepoPath(opts.Path).WriteVersion`

File: ipfs-10-to-11/migration/migration.go [hunk 1]
```diff
@@ -49,7 +49,18 @@ func (m Migration) Apply(opts migrate.Options) error {
 	ctx, cancel := context.WithCancel(context.Background())
 	defer cancel()
 
-	if err = transferPins(ctx, opts.Path); err != nil {
+	if !fsrepo.IsInitialized(opts.Path) {
+		return fmt.Errorf("ipfs repo %q not initialized", opts.Path)
+	}
```
Comment (aschmahmann) [inline ipfs-10-to-11/migration/migration.go:54]: Why is this only used for Apply and not for Revert?

Comment (gammazero) [reply ipfs-10-to-11/migration/migration.go:54]: Following example from previous migrations.

Done in both places now.

**Review by aschmahmann — APPROVED** [review]
